### ISSUE TITLE
Formatting broken for some translated pages

### ISSUE THREAD

**Issue by Mirzipan** [Mirzipan/Homm3_BG_Database#8]
STR:
1) open any individual card in astrologers proclaim or events directory.
2) switch language to `en`.
3) switch language to `pl`.
2) observe that it is much larger than intended and contains text in `{ }` underneath.

seems to have broken with the `localization` merge.

en:
![image](https://github.com/user-attachments/assets/4d56c760-f8fb-4460-8f9e-1ea37905f402)

pl:
![image](https://github.com/user-attachments/assets/ce94b14c-c354-4e31-a7f3-7cea2ff63840)

**Comment by qwrtln** [comment]
Yeah, it seems that `po4a` has trouble parsing HTML inside Markdown. We can work around this by increasing the required translation's threshold. In that case, files with only a single line translated will be omitted from the markdown generation, and originals will be used as fallback: https://github.com/Mirzipan/Homm3_BG_Database/pull/9

**Comment by qwrtln** [comment]
Looks good now.

**Comment by Mirzipan** [comment]
fixed
